version: '1.1'

services:
  app:
    image: librarydemo
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/librarydemo?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
  db:
    image: postgres
    environment:
      DATABASE_HOST: docker-postgres
      DATABASE_PORT: 5432
      POSTGRES_DB: librarydemo
      POSTGRES_PASSWORD: root
      POSTGRES_ROOT_PASSWORD: root